name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby
    strategy:
      matrix:
        ruby:
          - '3.0.2'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'yarn'
    
    - name: Setup CI
      run: make ci-setup

    - name: Check
      run: make check
    
    - name: Test coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CB_TEST_ID }}
      with:
        coverageCommand: make test
